
stages:
  - build

build_img:
  stage: build
  tags:
    - dind
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then exit 0; fi
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
